import type { Locale } from './i18n';

const adminMessages = {
  en: {
    brand: {
      name: 'ClawScale Admin',
      tagline: 'Operations shell',
    },
    layout: {
      title: 'Admin console',
      signOutTitle: 'Sign out',
      nav: [
        { href: '/admin/customers', label: 'Customers', exact: false },
        { href: '/admin/channels', label: 'Channels', exact: false },
        { href: '/admin/deliveries', label: 'Deliveries', exact: false },
        { href: '/admin/agents', label: 'Agents', exact: false },
        { href: '/admin/admins', label: 'Admins', exact: false },
      ],
      roleLabel: 'Admin account',
    },
    common: {
      loading: 'Loading...',
      errorPrefix: 'Error',
      empty: 'No records found.',
      retry: 'Retry',
      cancel: 'Cancel',
      close: 'Close',
      readOnly: 'Read-only',
      readOnlyDescription: 'Operational reference only. Changes stay on the API side for now.',
    },
    paging: {
      previous: 'Previous',
      next: 'Next',
      summary: (from: number, to: number, total: number) => 'Showing ' + from + '-' + to + ' of ' + total,
    },
    login: {
      title: 'Admin sign in',
      description: 'Use an AdminAccount to access the admin backend MVP.',
      emailLabel: 'Email',
      passwordLabel: 'Password',
      submit: 'Sign in',
      submitting: 'Signing in...',
      genericError: 'We could not sign you in right now.',
      invalidCredentials: 'The AdminAccount email or password is incorrect.',
      inactiveAccount: 'This AdminAccount is inactive.',
    },
    customers: {
      title: 'Customers',
      subtitle: 'Read-only customer, ownership, and channel coverage view.',
      columns: {
        customer: 'Customer',
        contactIdentifier: 'Contact identifier',
        claimStatus: 'Claim status',
        registered: 'Registered',
        firstSeen: 'First seen',
        agent: 'Agent',
        channels: 'Channels',
      },
    },
    channels: {
      title: 'Channels',
      subtitle: 'Read-only customer channel inventory with admin filters.',
      filters: {
        status: 'Status',
        kind: 'Kind',
        allStatuses: 'All statuses',
        allKinds: 'All kinds',
      },
      columns: {
        name: 'Channel',
        kind: 'Kind',
        status: 'Status',
        customerId: 'Customer ID',
        updated: 'Updated',
      },
    },
    deliveries: {
      title: 'Failed deliveries',
      subtitle: 'Recent failed outbound deliveries only.',
      filters: {
        channelId: 'Channel ID',
        apply: 'Apply filter',
        clear: 'Clear',
      },
      columns: {
        delivery: 'Delivery',
        tenantId: 'Tenant',
        channelId: 'Channel',
        idempotencyKey: 'Idempotency key',
        error: 'Error',
        updated: 'Updated',
      },
    },
    agents: {
      title: 'Agents',
      subtitle: 'Single-agent operational record for Coke.',
      fields: {
        slug: 'Slug',
        endpoint: 'Endpoint',
        tokenConfigured: 'Token configured',
        defaultAgent: 'Default agent',
        healthStatus: 'Handshake health',
        healthSource: 'Health source',
        observedAt: 'Observed at',
        createdAt: 'Created',
        updatedAt: 'Updated',
      },
    },
    admins: {
      title: 'Admins',
      subtitle: 'Manage AdminAccount access to the admin backend MVP.',
      addAdmin: 'Add admin',
      addTitle: 'Create admin account',
      emailLabel: 'Admin email',
      passwordLabel: 'Temporary password',
      createSubmit: 'Create admin',
      removeTitle: 'Remove admin',
      confirmRemove: 'Remove this admin account?',
      genericError: 'The admin change could not be completed.',
      columns: {
        email: 'Email',
        status: 'Status',
        createdAt: 'Created',
        updatedAt: 'Updated',
        actions: 'Actions',
      },
      statusLabels: {
        active: 'Active',
        inactive: 'Inactive',
      },
    },
  },
  zh: {
    brand: {
      name: 'ClawScale 管理后台',
      tagline: '运维控制台',
    },
    layout: {
      title: '管理控制台',
      signOutTitle: '退出登录',
      nav: [
        { href: '/admin/customers', label: '客户', exact: false },
        { href: '/admin/channels', label: '渠道', exact: false },
        { href: '/admin/deliveries', label: '投递', exact: false },
        { href: '/admin/agents', label: '代理', exact: false },
        { href: '/admin/admins', label: '管理员', exact: false },
      ],
      roleLabel: '管理员账号',
    },
    common: {
      loading: '加载中...',
      errorPrefix: '错误',
      empty: '暂无记录。',
      retry: '重试',
      cancel: '取消',
      close: '关闭',
      readOnly: '只读',
      readOnlyDescription: '当前仅提供运维查看，修改操作仍通过 API 处理。',
    },
    paging: {
      previous: '上一页',
      next: '下一页',
      summary: (from: number, to: number, total: number) => '显示 ' + from + '-' + to + ' / ' + total,
    },
    login: {
      title: '管理员登录',
      description: '使用 AdminAccount 访问管理后台 MVP。',
      emailLabel: '邮箱',
      passwordLabel: '密码',
      submit: '登录',
      submitting: '登录中...',
      genericError: '暂时无法登录，请稍后再试。',
      invalidCredentials: '管理员邮箱或密码不正确。',
      inactiveAccount: '该管理员账号已停用。',
    },
    customers: {
      title: '客户',
      subtitle: '只读查看客户、归属和渠道覆盖情况。',
      columns: {
        customer: '客户',
        contactIdentifier: '联系标识',
        claimStatus: '认领状态',
        registered: '注册时间',
        firstSeen: '首次出现',
        agent: '代理',
        channels: '渠道',
      },
    },
    channels: {
      title: '渠道',
      subtitle: '带筛选的客户渠道只读清单。',
      filters: {
        status: '状态',
        kind: '类型',
        allStatuses: '全部状态',
        allKinds: '全部类型',
      },
      columns: {
        name: '渠道',
        kind: '类型',
        status: '状态',
        customerId: '客户 ID',
        updated: '更新时间',
      },
    },
    deliveries: {
      title: '失败投递',
      subtitle: '仅展示最近失败的 OutboundDelivery 记录。',
      filters: {
        channelId: '渠道 ID',
        apply: '应用筛选',
        clear: '清除',
      },
      columns: {
        delivery: '投递',
        tenantId: '租户',
        channelId: '渠道',
        idempotencyKey: '幂等键',
        error: '错误',
        updated: '更新时间',
      },
    },
    agents: {
      title: '代理',
      subtitle: 'Coke 单代理运维记录。',
      fields: {
        slug: 'Slug',
        endpoint: 'Endpoint',
        tokenConfigured: '已配置令牌',
        defaultAgent: '默认代理',
        healthStatus: '握手健康',
        healthSource: '健康来源',
        observedAt: '观察时间',
        createdAt: '创建时间',
        updatedAt: '更新时间',
      },
    },
    admins: {
      title: '管理员',
      subtitle: '管理 AdminAccount 对后台 MVP 的访问。',
      addAdmin: '新增管理员',
      addTitle: '创建管理员账号',
      emailLabel: '管理员邮箱',
      passwordLabel: '临时密码',
      createSubmit: '创建管理员',
      removeTitle: '移除管理员',
      confirmRemove: '确认移除此管理员账号？',
      genericError: '管理员操作失败。',
      columns: {
        email: '邮箱',
        status: '状态',
        createdAt: '创建时间',
        updatedAt: '更新时间',
        actions: '操作',
      },
      statusLabels: {
        active: '启用',
        inactive: '停用',
      },
    },
  },
} satisfies Record<Locale, unknown>;

export function getAdminCopy(locale: Locale) {
  return adminMessages[locale];
}
